<?php

namespace Database\Seeders;

use App\Models\Editeur;
use Illuminate\Database\Seeder;

class EditeursSeederTable extends Seeder {
    const editeurs = [
        '1-2-3-Games',
        '1A Games',
        '2d Sans Faces',
        '404 Editions',
        '4Dados',
        '7ème Cercle',
        'Abacus Spiele',
        'Academy Games',
        'ACIES Edizioni',
        'Act in Games',
        'ADG',
        'Advancing FIre',
        'AEG',
        'Agate',
        'AGEOD',
        'Ajax Games',
        'AKA Games',
        'Ankama',
        'Arcane Tinmen',
        'Ares Games',
        'Arkhane Asylum Publishing',
        'Asmodée éditions',
        'Asyncron',
        'Atalia',
        'AV Studio Games',
        'Avalanche Press',
        'Avalon Hill',
        'Bad Taste Games',
        'Bankiiiz Editions',
        'Battle Bunker Games',
        'Bayard Jeux',
        'Beleduc',
        'Bellica 3rd Generation',
        'Bibliothèque Interdite',
        'Bioviva !',
        'Black Book editions',
        'Black Chantry Production',
        'Blackrock Games',
        'Blam',
        'Blue Cocker',
        'Blue Orange',
        'Blue Panther LLC',
        'Bombyx',
        'Borderline Editions',
        'Bounding Fire Productions',
        'Bragelonne',
        'Brain Games',
        'Buzzy Games',
        'Capsicum Games',
        'Captain Macaque',
        'Catch Up Games',
        'Cerigo Editions',
        'Chessex',
        'Clash of Arms',
        'Clever Mojo Games',
        'Cocktail Games',
        'Columbia Games',
        'Compass Games',
        'Consim Press',
        'Cranio Creations',
        'Critical Hit',
        'Crosscut Games',
        'Dan Verssen Games',
        'daVinci Games',
        'Days of Wonder',
        'Decision Games',
        'Département des sombres projets',
        'Devil Pig Games',
        'Devir',
        'Diffraction Entertainment',
        'Diptic Games',
        'DLD',
        'DLP Games',
        'Don\'t Panic Games',
        'Draco Ideas',
        'Dragon Dawn Productions Tuonela Productions Ltd',
        'Dujardin',
        'Eagle Gryphon Games',
        'Echec et Pat',
        'Eclipse Editorial',
        'Edge Entertainment',
        'Éditions Dagda',
        'Éditions du Hibou',
        'Editions Icare',
        'Éditions Sans Détour',
        'Elite Games',
        'Euphoria Games',
        'Europa Simulazioni',
        'Facily Jeux',
        'Fantastic Lombric',
        'Fantasy Flight games',
        'Ferti',
        'Fiery Dragon',
        'Fifth Column Games',
        'Filosofia',
        'Fireside Games',
        'Flatlined Games',
        'Flip Flap Editions',
        'Flying Frog Productions',
        'Flying Pig Games',
        'France Cartes',
        'Fred Games',
        'Funforge',
        'Gale Force Nine',
        'Game Brewer',
        'Gameflow',
        'Games Workshop',
        'Gameworks',
        'GD Jeux',
        'Geek Attitude Games',
        'Gen-X Games',
        'Gigamic',
        'GMT Games',
        'Goldsieber',
        'Goliath Games',
        'Gorilla Games',
        'Granna',
        'Grenier Games',
        'Griggling Games',
        'Grosso Modo Editions',
        'GRRRE Games',
        'Hanayama',
        'hans im glück',
        'Hasbro',
        'Hazgaard Editions',
        'Helvetia Games',
        'Hexagonal',
        'Hiboutatillus',
        'High Flying Dice Games',
        'Histogame',
        'Histoire &amp; Collections',
        'Historic\'one',
        'Hobby World',
        'Holy Grail Games',
        'HPS Simulations',
        'Huch ! &amp; friends',
        'Hurrican',
        'Id&amp;aL Editions',
        'Iello',
        'Igiari',
        'ilopeli',
        'In Ludo Veritas',
        'Intrafin',
        'Jactalea',
        'Jeux Opla',
        'John Doe',
        'Jolly Roger Games',
        'Khaos Project',
        'Khyber Pass Games',
        'Kikigagne?',
        'Kolossal Games',
        'Kosmos',
        'Krok Nik Douil',
        'Krok Nik Douil Éditions',
        'L2',
        'La Boite à Heuhh',
        'La boite de jeu',
        'La haute roche',
        'La Mame Games',
        'La Voix de Rokugan',
        'Lapin Marteau',
        'Lautapelit',
        'Le Droit de Perdre',
        'Le Franc Tireur',
        'Le Grimoire',
        'Le Joueur',
        'Le scorpion masqué',
        'Legion Distribution',
        'Legion Wargames',
        'Leonardo Games',
        'Les écuries d\'Augias',
        'Les Éditions du Troisième Oeil',
        'Les Jeux du Griffon',
        'Letheia',
        'Libellud',
        'Lifestyle Boardgames',
        'Lo Scarabeo',
        'Lock \'N Load Publishing',
        'Lucky Duck Games',
        'Ludically',
        'Ludifolie editions',
        'Ludimaniac',
        'Ludocom',
        'Ludonaute',
        'Lui-Même',
        'Lumberjacks Studio',
        'Mangrove Games',
        'Mantic',
        'Marabunta',
        'Matagot',
        'MATTEL',
        'Mayday Games',
        'Mayfair Games',
        'MCS Group',
        'Melissa &amp; Doug',
        'Mercury Games',
        'Mind Fitness Games',
        'Mongoose Publishing',
        'Monolith',
        'Moonster Games',
        'Multi-Man Publishing',
        'Multifaces Éditions',
        'MushrooM games',
        'Narrativiste Editions',
        'NECA',
        'Nexus',
        'Nuts Publishing',
        'Oeuf Cube éditions',
        'oh mygame',
        'Oink Games',
        'Oka Luda',
        'Old Casa Games',
        'OldChap Games',
        'Oliphante Giochi',
        'On the go editions',
        'One Small Step',
        'Operational Studies Group',
        'Oriflam',
        'Origames',
        'Osprey Games',
        'OYA',
        'Paille éditions',
        'Paizo',
        'Paradox Interactive',
        'Pavillon noir',
        'Pearl Games',
        'Pegasus',
        'Pencil First Games',
        'Pendragon game studio',
        'Petersen Games',
        'Petit Joueur',
        'Petroglyph',
        'Phalanx',
        'Pink Monkey Games',
        'Pixie Games',
        'Plaid Hat Games',
        'Plan B Games',
        'Play &amp; Win',
        'Play Factory',
        'Playad games',
        'Pleasant Company Games',
        'Pratzen Editions',
        'Pretzel Games',
        'PSC Games',
        'Purple Brain',
        'Q-Workshop',
        'Queen Games',
        'QWG Games',
        'R&amp;D Games',
        'Rackham Entertainment',
        'Raise Dead Editions',
        'Ravensburger',
        'Renegade Game Studios',
        'Repos Prod',
        'Revolution Games',
        'Rio Grande Games',
        'River Horse',
        'Rosebud',
        'Runes Editions',
        'Schmidt',
        'Scriptarium',
        'Serious Poulp',
        'Shakos',
        'Sierra Madre Games',
        'Simmons Games',
        'Sit Down !',
        'Sofa Games',
        'Sophisticated Games',
        'Sorry We Are French',
        'Space Cowboys',
        'Sphere Games',
        'Spin Master',
        'Spot Games',
        'Steamforged Games',
        'Stratagem Game Design',
        'Strategemata',
        'Studio DeadCrows',
        'Subverti',
        'Super Meeple',
        'Superlude',
        'Sweet November',
        'Taban Miniatures',
        'Tablestar Games',
        'Tactic',
        'Take on You',
        'Terres étranges',
        'The Broken Token',
        'The Flying Games',
        'The Pokémon Company',
        'The Red Joker',
        'Think Fun',
        'Tiki Editions',
        'Tilsit',
        'TMG',
        'Trafalgar Editions',
        'Treefrog',
        'Trefl Joker Line',
        'Triton Noir',
        'TSR',
        'Turning Point Simulations',
        'UGG',
        'Ultra Pro',
        'upgames',
        'Upper Deck',
        'Valley Games',
        'Ventonuovo Games',
        'Victory Point Games',
        'Warfrog',
        'WarriorElite',
        'WBS Games',
        'What\'s Your Game ?',
        'White Dog Games',
        'White Goblin Games',
        'White Wizard Games',
        'Whyme',
        'Wizards of the Coast',
        'Wizkids',
        'Wogamat',
        'Word Forge Games',
        'Worthington Publishing',
        'XII Singes',
        'XPeditions',
        'Ynnis Éditions',
        'Yoka By Tsume',
        'Ystari',
        'Z-Man',
        'Zoch',
        'Zvezda'];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        for($i = 0; $i < count(self::editeurs); $i+=10){
            $editeur = new Editeur();
            $editeur->nom = self::editeurs[$i];
            $editeur->save();
        }
    }
}
